title: Qizhen Wu's Homepage
page-top-title: Qizhen Wu
top-section-bg-text: Event-based swarm intelligent decision "事件驱动群体智能决策"
home-subtitle: Qizhen Wu&ensp;|&ensp;吴其臻
copyright-text: '&copy; Qizhen Wu 2023-2025. All Rights Reserved.'
